PORT=9000

MONGODB_URL=mongodb://127.0.0.1:27017/lms

JWT_SECRET=mysecret123
JWT_EXPIRY=1d

FRONTEND_URL=http://localhost:5173

CONTACT_US_EMAIL=test@gmail.com

CLOUDINARY_CLOUD_NAME=dummy
CLOUDINARY_API_KEY=dummy
CLOUDINARY_API_SECRET=dummy

SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=test@gmail.com
SMTP_PASSWORD=testpassword
SMTP_FROM_EMAIL=test@gmail.com

RAZORPAY_KEY_ID=test_key
RAZORPAY_SECRET=test_secret
RAZORPAY_PLAN_ID=test_plan